version: '2'
services:
    rabbitmq_api:
        container_name: rabbitmq_api
        image: neitonjc/rabbitmq_api:0.0.6
        ports:
            - 8081:8081
        environment:
            SPRING_RABBITMQ_HOST: 10.100.4.74
            SPRING_RABBITMQ_PORT: 5672
            SPRING_RABBITMQ_USERNAME: admin
            SPRING_RABBITMQ_PASSWORD: admin
