services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        restart: always
        ports: 
            - 5672:5672
            - 15672:15672
        volumes:
            - ./dados:/var/lib/rabbitmq/
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin
            
    mysql:
        image: mysql:5.7.31
        container_name: 'database-node'
        command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
        restart: always
        ports: 
            - 3306:3306
        environment: 
            - MYSQL_ROOT_PASSWORD=root
            - TZ=America/Sao_Paulo
        entrypoint:
              sh -c "
                echo 'CREATE DATABASE IF NOT EXISTS db_crud_rmq;' > /docker-entrypoint-initdb.d/init.sql;
                /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
              "
